In [97]:
from pymatgen.ext.matproj import MPRester
from pymatgen.io.cif import CifWriter
from pymatgen import Lattice 
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.core.structure import Structure, Molecule
from pymatgen.symmetry.structure import SymmetrizedStructure
from pymatgen.core.structure import PeriodicSite
from pymatgen.core.operations import SymmOp
from pymatgen.util.coord import find_in_coord_list, pbc_diff
from pprint import pprint
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
import matplotlib.image as mpimg
import numpy as np
import matplotlib.pyplot as plt

with MPRester("QpfJCrDNtAVubMxG") as m:
    # Structure for material id
    structure = m.get_structure_by_material_id("mp-7478")
    
    # Creation of the CIF file
    w = CifWriter(structure)
    CIF=w.write_file('RbTmO2_mp-7478.cif')
    

SgA=SpacegroupAnalyzer(structure)

# The structure in a conventional standardized cell 
ConvStand=SpacegroupAnalyzer(SgA.get_conventional_standard_structure())
ConvStandSite=ConvStand.get_conventional_standard_structure().sites

Symop=ConvStand.get_symmetry_operations()
Sym1=Symop[2]
Sym2=Symop[7]
Sym3=Symop[12]
print("Rotation d'ordre 3")
print("__________________________")
print("")
print("L'élément de symétrie numéro 3 sur jmol correspond à un axe de rotation d'ordre 3.Comme on le voit sur la figure ci-dessous,"
      "tout élément initialment situé en (x, y, z) aura après transformation les coordonnnées ("+Sym1.as_xyz_string()+").")
print("Dans notre cas nous avons l'atome de Rb qui passe des coordonnées (0.67,0.33,0.33) aux coordonnées")
print(Sym1.operate((0.67,0.33,0.33)))
print("")
print("On peut associer à cette transformation une matrice de rotation et un vecteur de translation ")
print("Matrice de rotation :")
print(Sym1.rotation_matrix)
print("Vecteur de translation :")
print(Sym1.translation_vector)
print("")
print("Pour trouver les nouvelles coordonnées après transformation, on multiplie les coordonnées de l'atome par la matrice de rotation et on ajoute le vecteur de translation.")
print("")
print("")
print("Plan miroir")
print("__________________________")
print("")
print("L'élément de symétrie numéro 8 sur jmol correspond à un plan miroir.Comme on le voit sur la figure ci-dessous,"
      "tout élément initialment situé en (x, y, z) aura après transformation les coordonnnées ("+Sym2.as_xyz_string()+").")
print("Dans notre cas nous avons l'atome de Tm qui passe des coordonnées (0.67,0.33,0.83) aux coordonnées")
print(Sym2.operate((0.67,0.33,0.83)))
print("")
print("On peut associer à cette transformation une matrice de rotation et un vecteur de translation ")
print("Matrice de rotation :")
print(Sym2.rotation_matrix)
print("Vecteur de translation :")
print(Sym2.translation_vector)
print("")
print("Pour trouver les nouvelles coordonnées après transformation, on multiplie les coordonnées de l'atome par la matrice de rotation et on ajoute le vecteur de translation.")
print("")
print("")
print("Translation")
print("__________________________")
print("")
print("L'élément de symétrie numéro 13 sur jmol correspond à une translation.Comme on le voit sur la figure ci-dessous,"
      "tout élément initialment situé en (x, y, z) aura après transformation les coordonnnées ("+Sym3.as_xyz_string()+").")
print("Dans notre cas nous avons l'atome de O qui passe des coordonnées (0.67,0.33,0.56) aux coordonnées")
print(Sym3.operate((0.67,0.33,0.56)))
print("")
print("On peut associer à cette transformation une matrice de rotation et un vecteur de translation ")
print("Matrice de rotation :")
print(Sym3.rotation_matrix)
print("Vecteur de translation :")
print(Sym3.translation_vector)
print("")
print("Pour trouver les nouvelles coordonnées après transformation, on multiplie les coordonnées de l'atome par la matrice de rotation et on ajoute le vecteur de translation.")
      

Rotation d'ordre 3
__________________________

L'élément de symétrie numéro 3 sur jmol correspond à un axe de rotation d'ordre 3.Comme on le voit sur la figure ci-dessous,tout élément initialment situé en (x, y, z) aura après transformation les coordonnnées (-y, x-y, z).
Dans notre cas nous avons l'atome de Rb qui passe des coordonnées (0.67,0.33,0.33) aux coordonnées
[-0.33  0.34  0.33]

On peut associer à cette transformation une matrice de rotation et un vecteur de translation 
Matrice de rotation :
[[ 0. -1.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]
Vecteur de translation :
[0. 0. 0.]

Pour trouver les nouvelles coordonnées après transformation, on multiplie les coordonnées de l'atome par la matrice de rotation et on ajoute le vecteur de translation.


Plan miroir
__________________________

L'élément de symétrie numéro 8 sur jmol correspond à un plan miroir.Comme on le voit sur la figure ci-dessous,tout élément initialment situé en (x, y, z) aura après transformation les coordonnnées (-

![rot.png](https://github.com/willemarte/lmapr1492/blob/master/rot.png?raw=true)
